implement receive email on successful signup
andela/Ah-backend-xmen pull request #11
Opened 2019-01-14 11:43 UTC by MuhweziDeo

#### What does this PR do?
implement receive email on successful signup

#### Description of Task to be completed?
- send an email to  a user's email they used on signup 
- verify the email once a user clicks on the verification link sent to their inbox

#### How should this be manually tested?
- fetch this branch by running the command git fetch origin `ft-registration-emial-verification-162725255` in the terminal.
- check into the branch `git checkout ft-registration-emial-verification-162725255`
- start the virtual environment `source venv/bin/activate`
- re-install requirements `pip install -r requirements.txt`
- make migrations using `python manage.py makemigrations`
- migrate to update database  using `python manage.py migrate`
-  run development server using `python manage.py runserver`
- using postman perform a post request on `http://localhost:8000/api/users/`  to register a user
- check console for a link in the format `localhost:8000/api/users/registration-confirmation/MzQ/52z-49bc0b91cdc08b29f3ec/`
- perform a get request on the link and a response will be returned confirm successfully confirming email

- run `coverage run --omit="*tests*,*init*,*migrations*,*wsgi*" --source="authors" manage.py test&&coverage report -m` in terminal

#### What are the relevant pivotal tracker stories?
[#162725255](https://www.pivotaltracker.com/story/show/162725255
<img width="57" alt="screen shot 2019-01-14 at 2 41 25 pm" src="https://user-images.githubusercontent.com/39124174/51110771-ca0b7980-180a-11e9-8c03-24f4f7a3e22a.png">
<img width="653" alt="screen shot 2019-01-14 at 2 41 39 pm" src="https://user-images.githubusercontent.com/39124174/51110772-ca0b7980-180a-11e9-91d8-095a9fb0d18a.png">

)

2019-01-14 19:18 UTC, kdaglas requested changes
the PR title is not following our PR conventions, maybe fix that as i test the branch

2019-01-15 06:41 UTC, malfahad reviewed
This commit seems to be missing a file. Can't find the utils file with the 'email verification token creator' class.

2019-01-15 06:43 UTC, ja-odur commented
@MuhweziDeo Since you did not add any dependency to the `requirement.txt` file, please dont include installing requirements in the `testing section.

2019-01-15 06:44 UTC, ja-odur commented
@MuhweziDeo You also do not need to makemigrations since the migrations are pushed to the `github`. you only need to migrate.

2019-01-15 06:45 UTC, ja-odur commented
@MuhweziDeo Please rename the test folders from `test_` to `test`

2019-01-15 06:47 UTC, ja-odur commented
@MuhweziDeo the screenshots in the PR should be in the `screenshots` section. please check the engineering playbook.

2019-01-15 07:19 UTC, MuhweziDeo commented
> @MuhweziDeo Since you did not add any dependency to the `requirement.txt` file, please dont include installing requirements in the `testing section.

@ja-odur  my bad was reusing PR message

2019-01-15 07:20 UTC, MuhweziDeo commented
> @MuhweziDeo the screenshots in the PR should be in the `screenshots` section. please check the engineering playbook.

@ja-odur  noted

2019-01-15 07:20 UTC, MuhweziDeo commented
> @MuhweziDeo Please rename the test folders from `test_` to `test`

@ja-odur  this no implication in anyway but will do

2019-01-15 07:21 UTC, MuhweziDeo commented
> This commit seems to be missing a file. Can't find the utils file with the 'email verification token creator' class.

@malfahad  sure

2019-01-15 08:11 UTC, kdaglas submitted a review, later dismissed

2019-01-15 08:14 UTC, kdaglas commented
Can also fix the spelling errors in your PR, for example, that email spelling and also start with a capital letter on the PR title

2019-01-16 13:05 UTC, mariamiah commented
<img width="674" alt="screen shot 2019-01-16 at 4 01 51 pm" src="https://user-images.githubusercontent.com/39744587/51250659-2061ef00-19a8-11e9-88ef-90e70fde847b.png">
Yes the code works well, though update the PR, and change this issue concerning the console, to direct check in the email

2019-01-16 15:51 UTC, calvinpete submitted a review, later dismissed
Looks Good To Me

2019-01-16 15:55 UTC, d-rita submitted a review, later dismissed
works fine. though be mindful of typos when creating the branch in future.

2019-01-16 15:56 UTC, MuhweziDeo commented
> works fine. though be mindful of typos when creating the branch in future.

@d-rita  my apologies to you and the team for that

2019-01-16 16:03 UTC, kdaglas submitted a review, later dismissed
ok done testing, the email is sent to show successful registration that is dope, tests are on point... LGTM

2019-01-16 16:06 UTC, ja-odur commented on authors/apps/authentication/tests_/test_endpoints.py
> +    def test_user_email_verification_email_sent(self):
@MuhweziDeo Please use the test `succeeds` convention instead of `sent`.

2019-01-16 16:06 UTC, ja-odur commented on authors/apps/authentication/tests_/test_model.py
> +            when __str__ is callted is should return a users email
@MuhweziDeo There is a typo here.

2019-01-16 16:06 UTC, ja-odur commented on authors/apps/authentication/tests_/test_model.py
> +            when get_short_name is callted is should return a users username
@MuhweziDeo typo here too.

2019-01-16 16:07 UTC, mariamiah submitted a review, later dismissed
LGTM

2019-01-16 16:11 UTC, kdaglas commented on authors/apps/authentication/tests_/test_model.py
> +            when __str__ is callted is should return a users email
I had not seen that... thanx @ja-odur

2019-01-16 16:13 UTC, kdaglas approved these changes

2019-01-16 16:17 UTC, ja-odur approved these changes
LGTM

2019-01-16 16:19 UTC, d-rita approved these changes

2019-01-16 16:22 UTC, merged

2019-01-16 16:43 UTC, kdaglas reviewed
LGTM