feat(comments): Track edit history
andela/Ah-backend-xmen pull request #36
Opened 2019-01-29 10:16 UTC by calvinpete

#### What does this PR do?
This PR enables users to be able to see the previous versions of comments made on an article after previous edits.

#### Description of Task to be completed?
The previous version of a modified comment should be retrievable on demand by either the author of the article or the author of the comment.

#### How should this be manually tested?
- First things first, fetch this branch by running the command `git fetch origin ft-comments-track-edit-history-162725275` in the terminal.
- Check into this branch by running `git checkout ft-comments-track-edit-history-162725275`
- Activate your virtual environment by running `source venv/bin/activate`
- Drop your current database and create a new one by running `create database <database name>;` and `drop database <database name>;` in the psql shell
- Apply the new changes to the models by running `python manage.py migrate`
- Start the application by running `python manage.py runserver`
- Click the `Run in postman` button to test the endpoint as shown in the screenshots below

The PR addresses `GET/api/articles/<slug>/comments/<comment_id>/history` endpoint

#### What are the relevant pivotal tracker stories?
[#162725275](https://www.pivotaltracker.com/story/show/162725275)

#### Screenshots

#### Comment edit history

#### No comment edit history

#### POSTMAN
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/f24ca45d27c7253a80d0)

2019-01-29 13:14 UTC, malfahad requested changes

2019-01-29 13:14 UTC, malfahad commented on authors/apps/comments/urls.py
> +          CommentHistoryView.as_view(), name='comment-history')
Please include this `previous_versions` endpoint in the PR as well. The PR mentions `history` instead.

2019-01-29 13:14 UTC, malfahad submitted a review, later dismissed

2019-01-30 11:56 UTC, mariamiah approved these changes
LGTM

2019-01-30 11:56 UTC, malfahad approved these changes

2019-01-30 11:56 UTC, MuhweziDeo approved these changes
@calvinpete  All good

2019-01-30 11:57 UTC, d-rita approved these changes

2019-01-30 11:57 UTC, merged