Add comment id to return body of comment reply
andela/Ah-backend-xmen pull request #48
Opened 2019-03-01 18:04 UTC by MuhweziDeo

**what this PR do?**
implement returning of a comment id in the body of a comment reply

**Tasks to be completed**
- add comment field to serializer

2019-03-01 18:24 UTC, d-rita submitted a review, later dismissed
LGTM

2019-03-01 18:26 UTC, kdaglas submitted a review, later dismissed
just a line LGTM

2019-03-04 01:15 UTC, calvinpete approved these changes
LGTM

2019-03-04 01:19 UTC, calvinpete requested changes
Please polish up the PR description in both grammar and content. Based on past experience, I'm sure it can not take you more than 2 minutes.

2019-03-04 10:03 UTC, malfahad commented
@calvinpete  cc @ja-odur , The requested changes have been implemented.

2019-03-04 10:46 UTC, calvinpete approved these changes

2019-03-04 11:03 UTC, kdaglas approved these changes
we actually needed that, quick fix

2019-03-04 11:39 UTC, d-rita approved these changes
LGTM

2019-03-04 11:50 UTC, closed without merging