chore(heroku): setup and deploy base application to heroku
andela/Ah-backend-xmen pull request #5
Opened 2019-01-08 20:08 UTC by armstrongsouljah

# What does this PR do?
   This PR is to set up and deploy base application to Heroku.
## Description of the task to be completed.
   Setup and deploy base application to Heroku so that other users can access the application.
# how should this be manually tested?
   - First things first, fetch this branch by running `git fetch origin ch-setup-app-and-deploy-to-heroku-162725250`
 - check into this branch by running ` git checkout -- ch-setup-app-and-deploy-to-heroku-162725250`
- activate your virtual environment by running `source venv/bin/activate`
- install dependencies by running `pip install -r requirements.txt`
-  navigate to [staging app](https://ah-backend-staging.herokuapp.com/api/`

# To run locally, you need to have a `heroku-cli` installed on your machine
    - run local Heroku  local server using `heroku local web`
   - navigate to `localhost:5000/api/` in your web browser
 # Relevant stories
   [#162725250](https://www.pivotaltracker.com/story/show/162725250)

2019-01-09 06:01 UTC, malfahad requested changes

2019-01-09 06:01 UTC, malfahad commented on authors/settings.py
>  DEBUG = True
DEBUG should not be true in production.
 Can you consider adding an IS_HEROKU check and set DEBUG accordingly?

2019-01-09 07:04 UTC, armstrongsouljah commented
Thanks for pointing out the `DEBUG` let me change it accordingly.

On Wed, 9 Jan 2019 at 09:01, Malende Fahad <notifications@github.com> wrote:

> *@malfahad* requested changes on this pull request.
> ------------------------------
>
> In authors/settings.py
> <https://github.com/andela/Ah-backend-xmen/pull/5#discussion_r246267058>:
>
> > @@ -19,12 +20,16 @@
>  # See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/
>
>  # SECURITY WARNING: keep the secret key used in production secret!
> -SECRET_KEY = '7pgozr2jn7zs_o%i8id6=rddie!*0f0qy3$oy$(8231i^4*@u3'
> +SECRET_KEY = config('SECRET_KEY')
>
>  # SECURITY WARNING: don't run with debug turned on in production!
>  DEBUG = True
>
> DEBUG should not be true in production.
> Can you consider adding an IS_HEROKU check and set DEBUG accordingly?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andela/Ah-backend-xmen/pull/5#pullrequestreview-190582194>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARbwlp44brJlx8BBRh_gZleJ-D6RiFPeks5vBYXOgaJpZM4Z2MGY>
> .
>

2019-01-09 07:13 UTC, armstrongsouljah commented on authors/settings.py
>  DEBUG = True
@malfahad I am working on editing `DEBUG` to use the environment variables on both the staging and production environments. Thus i won't need  `IS_HEROKU`, am instead going to use `IS_STAGING` and `IS_PRODUCTION`.

2019-01-09 07:50 UTC, armstrongsouljah commented on authors/settings.py
>  DEBUG = True
@malfahad and team, I have updated the `DEBUG` constant in `settings.py` to point to environment variables on Heroku for both staging and production environments.

2019-01-09 08:11 UTC, malfahad submitted a review, later dismissed

2019-01-09 09:24 UTC, calvinpete submitted a review, later dismissed
@armstrongsouljah Everything looks fine to me

2019-01-09 10:47 UTC, mariamiah commented
@armstrongsouljah Code looks okay but can you grant access or add me as a collaborator, seems I cannot access the application

2019-01-09 11:18 UTC, armstrongsouljah commented
@mariamiah. I used  Deo Muhwezi's account to create the applications and
he's the only one with access to the application.  Only he can add you as a
collaborator.

On Wed, 9 Jan 2019 at 13:47, mariamiah <notifications@github.com> wrote:

> @armstrongsouljah <https://github.com/armstrongsouljah> Code looks okay
> but can you grant access or add me as a collaborator, seems I cannot access
> the application
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/andela/Ah-backend-xmen/pull/5#issuecomment-452653572>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARbwliBSiUeSWvaY2-DynCwVsEvFMWPqks5vBcjcgaJpZM4Z2MGY>
> .
>

2019-01-09 12:31 UTC, MuhweziDeo submitted a review, later dismissed

2019-01-09 12:31 UTC, MuhweziDeo commented on authors/urls.py
> +if settings.DEBUG:
@armstrongsouljah Are u collecting static files locally

2019-01-10 06:44 UTC, malfahad submitted a review, later dismissed

2019-01-10 08:57 UTC, MuhweziDeo submitted a review, later dismissed

2019-01-10 10:58 UTC, d-rita submitted a review, later dismissed

2019-01-10 13:21 UTC, MuhweziDeo submitted a review, later dismissed

2019-01-10 13:21 UTC, kdaglas submitted a review, later dismissed
Makes more sense after your explanation, so great stuff

2019-01-10 13:21 UTC, malfahad submitted a review, later dismissed

2019-01-10 13:21 UTC, calvinpete submitted a review, later dismissed
@armstrongsouljah LGTM

2019-01-10 13:21 UTC, mariamiah submitted a review, later dismissed
LGTM

2019-01-10 13:23 UTC, d-rita submitted a review, later dismissed

2019-01-10 13:32 UTC, MuhweziDeo approved these changes

2019-01-10 13:33 UTC, calvinpete approved these changes
@armstrongsouljah LGTM

2019-01-10 13:34 UTC, mariamiah approved these changes

2019-01-10 13:34 UTC, merged